theme: jekyll-theme-minimal
title: Zhuo Chen 陈卓
description: Welcome to my website! My name is Zhuo Chen 陈卓. I was born and raised up in Wuhan, China. I got my bachelor degree in Engineering Mechanics in Tongji University in 2012. I switched to Astrophysics in 2013 at the University of Rochesteri and joined Adam Frank's computional astrophysics group. In 2018, I graduated from the University of Rochester. I am now a CITA national postdoctoral fellow at the University of Alberta and will join Tsinghua University as a Tsinghua Astrophysics Outstanding fellow in 2020.
show_downloads: false
google_analytics: UA-173850039-1
